accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns= [
    #path('signup', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
]

resumehub/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, include

# Customise admin headings
admin.site.site_header = "ResumeHub Admin"
admin.site.site_title = "ResumeHub Admin Portal"
admin.site.index_title = "Welcome to ResumeHub Admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    # Resume specific paths
    path('resumes/', include('resumes.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),
]

resumes/urls.py
from django.urls import path, include
from . import views

app_name = 'resumes'

urlpatterns= [

    # All resumes
    path('', views.resumes, name='resumes'),

    # Individual resume
    path('<slug>', views.resume, name='resume'),

]

frontend/models.py
from django.db import models

# Create your models here.

resumes/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.contrib.auth.models import User
from qualities.models import Education
from companies.models import Company

# Create your models here.
# Resume 
class Resume(models.Model):
    """
    Holds Resume created by the candidate.
    """
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(verbose_name='name', max_length=100, blank=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.SET_NULL, blank=True, null=True)
    slug = models.SlugField(verbose_name='slug', null=True, blank=True)
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    summary = models.TextField(verbose_name='Summary', null=True, blank=True)
    
    # Education level choices
    education = models.PositiveSmallIntegerField('Educational qualifications (recent N, 0 for none)', default=0)

    # Options
    include_address = models.BooleanField(verbose_name='Include Address', default=True)
    include_contact_number = models.BooleanField(verbose_name='Include Contact Number', default=True)
    include_email_id = models.BooleanField(verbose_name='Include Email ID', default=True)
    target_company = models.ManyToManyField(Company, verbose_name='Target Companies')

#     skills = models.TextField(verbose_name='Skills')
#     achievements = models.ManyToManyField(Achievement, verbose_name='Achievements')
#     projects = models.ManyToManyField(Project, verbose_name='Projects')
#     additional_sections = models.TextField(verbose_name='Additional Sections', blank=True)
#     work_experience = models.ForeignKey(WorkExperience, verbose_name='Work Experience', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
            value = self.unique_id
            self.slug = slugify(value, allow_unicode=True)
            super().save(*args, **kwargs)

frontend/views.py
from django.shortcuts import render

# Create your views here.

resumes/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from resumes.models import Resume

# Create your views here.

@login_required(login_url = 'accounts:login')
def resumes(request):
    resumes = Resume.objects.filter(candidate=request.user)
    context = {
        'user':request.user,
        'resumes': resumes
    }
    return render(request, 'resumes/resumes.html', context)

@login_required(login_url = 'accounts:login')
def resume(request, slug):
    context = {
        'user': request.user,
        'slug':slug
    }
    return render(request, 'resumes/resume.html', context)

frontend/templates/resumes/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{slug}}</title>
  
</head>
<body>

      <title>[Your Name] Resume</title>
      <style>
        /* Add your CSS styles here */
        body {
          font-family: Arial, sans-serif;
          margin: 0; /* Remove default body margin */
          /* Adjust following margins for A4-like size on printing */
          /* You might need to fine-tune these values based on your printer settings */
          margin: 2.5cm 3cm 2cm 3cm;
        }
        .container {
          width: 700px; /* Adjust width as needed */
          margin: 0 auto; /* Center horizontally */
          padding: 20px;
          border: 1px solid #ddd; /* Optional border for a resume look */
        }
        .header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }
        .header h1 {
          font-size: 24px;
          margin: 0;
        }
        .contact-info {
          text-align: right;
        }
        .section {
          margin-bottom: 20px;
        }
        .section h2 {
          font-size: 18px;
          margin-bottom: 5px;
        }
        .experience, .education {
          margin-top: 0; /* Remove default margin-top */
        }
        .experience li, .education li {
          margin-bottom: 5px;
        }
      </style>
    
      <div class="container">
        <header class="header">
          <h1>[Your Name]</h1>
          <div class="contact-info">
            <p>[Your Contact Information (Email, Phone Number, Location)]</p>
          </div>
        </header>
    
        <section class="section">
          <h2>Profile Summary</h2>
          <p>[A brief overview of your skills and experience relevant to the job you're applying for]</p>
        </section>
    
        <section class="section experience">
          <h2>Employment History</h2>
          <ul>
            <li>
              <h3>[Job Title]</h3>
              <h4>[Company Name] - [Dates of Employment]</h4>
              <ul>
                <li>[Key responsibility or achievement]</li>
                <li>[Key responsibility or achievement]</li>
              </ul>
            </li>
            <li>
              <h3>[Job Title]</h3>
              <h4>[Company Name] - [Dates of Employment]</h4>
              <ul>
                <li>[Key responsibility or achievement]</li>
                <li>[Key responsibility or achievement]</li>
              </ul>
            </li>
          </ul>
        </section>
    
        <section class="section education">
          <h2>Education</h2>
          <ul>
            <li>
              <h3>[Qualification Name]</h3>
              <h4>[University/College Name] - [Dates of Attendance]</h4>
              <p>[Optional: Mention relevant coursework or achievements]</p>
            </li>
            <li>
              <h3>[Qualification Name]</h3>
              <h4>[University/College Name] - [Dates of Attendance]</h4>
              <p>[Optional: Mention relevant coursework or achievements]</p>
            </li>
          </ul>
        </section>
    
        <section class="section skills">
          <h2>Skills</h2>
          <ul>
            <li>[Skill 1]</li>
            <li>[Skill 2]</li>
          </ul>
        </section>
      </div>
    

  <h2>Resume of user: {{user}}</h2>

  <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button class="dropdown-item" type="submit">Sign out</button>
  </form>

</body>
</html>